Crew-Wiki/crew-wiki-next

client/src/api/document.ts
client/src/api/images.ts
client/src/app/api/post-document/route.ts
client/src/app/api/put-document/route.ts
client/src/app/wiki/[title]/edit/layout.tsx
client/src/app/wiki/[title]/edit/page.tsx
client/src/app/wiki/[title]/page.tsx
client/src/app/wiki/post/page.tsx
client/src/components/Document/DocumentHeader.tsx
client/src/components/MarkdownEditor/index.tsx
client/src/components/RecentlyEdit/index.tsx
client/src/constants/cache.ts
client/src/context/DocumentWriteContext.tsx
client/src/hooks/fetch/useGetDocumentByTitle.ts
client/src/hooks/mutation/usePostDocument.ts
client/src/hooks/mutation/usePutDocument.ts
client/src/hooks/useFetch.ts
client/src/hooks/useMutation.ts
client/src/import-env.d.ts
client/src/utils/getEditorContents.ts
client/src/utils/http.ts
client/src/utils/replaceLocalUrlToS3Url.ts
client/src/utils/validation/title.ts

- close #5 
문서를 수정하는 기능을 옮겨왔습니다. 역시 제목은 수정할 수 없으며 편집자와 내용을 변경하여 작성완료를 누르면 문서가 수정됩니다.
크루위키는 /wiki/ 하위에 닉네임이 오는 구조입니다. 이런 구조에서 ISR을 활용하려면 /wiki/쿠키, /wiki/대문, /wiki/토다리 이런 문서들을 서버에서 미리 만들어두고 요청 시 응답을 내려줘야 합니다.
이 작업을 하기 위해 generateStaticParams라는 next에서 미리 정의된 함수를 사용하게 됩니다.
```ts
export async function generateStaticParams() {
const documents = await getRecentlyDocuments();
return documents.map(({title}) => ({title}));
}
```
사전 빌드 작업에서 최근 문서 정보를 들고 와서 크루위키에 등록된 제목을 추출합니다. 그 뒤 Page함수에서 하나하나 서버로 요청하여 문서마다 완성된 문서를 만들어두게 됩니다.
그리고 상단에 아래 두 개를 선언하게 됩니다.
revalidate는 재검증 시간이며 특정 시간이 지나면 서버에서 다시 html을 만들게 됩니다.
dynamicParams는 generateStaticParams에 정의되지 않은 params가 왔을 때 어떻게 처리할 것인지 정해줍니다. true로 설정한다는 것은 대체 페이지를 보여주겠다는 의미가 됩니다. (fallback은 다음 이슈에서 처리하겠습니다)
```ts
export const revalidate = …
```

문서 수정 기능 마이그레이션

---

client/src/api/document.ts
client/src/app/wiki/[title]/log/[logId]/page.tsx
client/src/app/wiki/[title]/logs/LogContent.tsx
client/src/app/wiki/[title]/logs/LogsHeader.tsx
client/src/app/wiki/[title]/logs/layout.tsx
client/src/app/wiki/[title]/logs/page.tsx
client/src/constants/cache.ts
client/src/constants/endpoint.ts

- close #9 
getDocumentLogsByTitle api를 서버에서 호출하여 편집 목록을 확인할 수 있도록 옮겨왔습니다.
(아직 static 처리는 아직. 이건 마이그레이션 이후 조정할 예정)
getSpecificDocumentLog api를 서버에서 호출하여 로그 상세를 확인할 수 있도록 옮겨왔습니다.
(이것도 static 처리는 아직. 이건 마이그레이션 이후 조정할 예정)

문서 편집 로그 마이그레이션

---

client/package.json
client/src/app/wiki/[title]/page.tsx
client/src/components/Document/DocumentContents.tsx
client/src/components/Document/toastui-editor-viewer.css
client/src/components/TOC/AttachTocClickHandler.tsx
client/src/components/TOC/TOC.tsx
client/src/utils/addDataIdToToc.ts
client/src/utils/markdownToHtml.ts
client/yarn.lock

- close #13 
Tui Viewer는 서버 사이드 렌더링을 지원하지 않아서 서버에서 실행시킬 수 없습니다. 그래서 단순히 뷰어를 담당하는 목적임에도 클라이언트에서 실행이 되어야 했습니다. 서버 사이드 렌더링을 채택했고, 위키의 많은 분량을 담당하는 것이 위키 문서 본문입니다. 그래서 Tui Viewer를 철거하고 직접 마크다운을 html로 변환하여 서버에서 완성된 html을 만들 수 있게 했습니다.
TOC가 간헐적으로 보이지 않던 문제도 Viewer의 문제였습니다. 기존에 TOC는 클라이언트 컴포넌트에서 Viewer가 로드된 후에 Viewer의 인스턴스 안에서 내부 html을 가져온 뒤 그 안에서 h1~6 태그를 가져오는 방식으로 구현했었습니다. 그러므로 TUI Editor가 클라이언트에서 실행될 때(다른 문서로 navigate한 뒤)는 문제가 일어나지 않으나, 문서를 새로고침해서 서버에서 다시 완성된 html을 받을 때 문제가 생기게 됩니다.
그래서 문서 본문과 TOC 모두를 서버에서 만든 뒤 클라이언트로 넘겨준다면 이러한 문제가 일어나지 않을 것 같아 시도했고 성공했습니다.
기존에 Viewer를 사용할 때는 단순히 마크다운을 넘겨주면 알아서 html로 변환해서 보여줬지만 Viewer를 철거 하다 보니 
파싱하는 과정을 추가해줘야 했습니다. 이를 직접 구현할까 고민했지만, 마크다운 문법, 그 내부의 html을 모두 파싱하는 코드를 작성하기에는 시간이 오래 걸릴 것 같아서 [unifiedjs](https://unifiedjs.com/learn/recipe/remark-html/) 라이브러리를 …

TOC가 정상적으로 보이도록 설정

---

client/src/app/wiki/[title]/error.tsx
client/src/app/wiki/[title]/log/[logId]/page.tsx

- close #15 
Next.js app router에서는 에러 화면이 필요한 디렉터리에 error.tsx를 적용하면 커스텀 에러를 보여줄 수 있습니다.
아래 디렉터리 구조를 React에서 바라보면
- app
- wiki
- layout.tsx
- page.tsx
- loading.tsx
- error.tsx
이렇게 변환할 수 있습니다.
```tsx
const Wiki = () => {
<Layout>
<ErrorBoundary FallbackComponent={<Error />}>
<Suspense fallback={<Loading />}>
<Page />
</Suspense>
</ErrorBoundary>
</Layout>
}
```
error.tsx를 정의하면 react에서 바라볼 때 에러 바운더리의 fallback이 실행되는 것이라고 생각하면 되며 그렇기 때문에 error.tsx는 클라이언트 컴포넌트이어야합니다.  브라우저에서 서버로 요청을 실행한 뒤에 에러가 발생해서 에러 바운더리가 보여지는 흐름이기 때문입니다.

오류 페이지 마이그레이션

---

client/src/app/wiki/[title]/edit/layout.tsx
client/src/app/wiki/[title]/log/[logId]/page.tsx
client/src/app/wiki/[title]/logs/page.tsx
client/src/app/wiki/[title]/page.tsx
client/src/app/wiki/post/layout.tsx
client/src/type/PageParams.type.ts

- close #17 
next.js는 SPA가 아니기 때문에 페이지 별로 다른 html이 생성됩니다
그러므로 페이지 별로 Meta tag를 다르게 가져갈 수 있고, 이를 적용하려고 합니다.
이유는 문서를 작성하고 공유했을 때 풍부한 정보를 제공하기 위함입니다.
아래 사진처럼 특정 문서를 공유했는데 사이트 제목과 사이트 전체 설명만 보이면 와닿지 않기 때문입니다.
각 페이지 성격에 맞는 Title과 description 그리고 메타태그를 설정했습니다.
서버 컴포넌트와 클라이언트 컴포넌트의 적용 방식이 조금 달라서 나누어 설명하겠습니다.
[next.js metadata](https://nextjs.org/docs/app/building-your-application/optimizing/metadata)를 참조하면서 설정했습니다.
공식문서에 따르면 메타 데이터를 정적, 동적으로 생성할 수 있다고 나와 있습니다.
정적의 경우 페이지 params와 관계없이 동일한 메타태그를 넣고 싶을 때, 동적일 경우 페이지 params에 따라 다르게 설정하고 싶을 때 사용합니다.
크루위키의 경우 쿠키(6기) 문서를 조회하면 쿠키(6기)에 대한 정보를 메타태그로 설정하고 싶기 때문에 동적 방식을 선택했습니다.
동적 방식은 next.js에서 미리 정의해 둔 generateMetadata를 선언하면 됩니다.
[title] 디렉터리로 title 파라미터를 받아서 아래 return에 적절하게 활용하면 됩니다.
여기서 백엔드로 api를 호출하여 작성자, 문서 본문까지 가져올 수 있으나, 이런 정보까지 보여줄 필요는 없을 것 같아서 호출하지 …

페이지 별 Meta tag 정의

---

client/src/components/common/RandomButton/useRandomButton.ts
client/src/components/layout/Header/RightHeader.tsx
client/src/components/layout/Header/WikiHeader.tsx

- close #29 
서버의 시점에서 봤을 때 어떤 브라우저에서 요청이 올지 (모바일, 데스크탑) 파악할 수 없습니다. 그래서 초기 값을 임의로 설정했다가 일어난 이슈입니다.
그래서 헤더의 우측 부분을 클라이언트에서 실행되도록 dynamic import를 사용했습니다.
```tsx
import dynamic from 'next/dynamic';
const RightHeader = dynamic(() => import('./RightHeader'), {ssr: false});
```
이렇게 한다면 RightHeader 컴포넌트는 서버에서 실행되지 않고 반드시 클라이언트에서 실행되고 초기값으로 window를 사용할 수 있습니다. 
```ts
const [isMobile, setIsMobile] = useState<boolean>(window.innerWidth <= 768);
```
https://github.com/user-attachments/assets/35cb6310-9687-46d0-8008-10443d008f64
아이콘 크기는 일정해졌지만 새로고침 시 랜덤 아이콘과 검색 창 전부 깜빡이는 현상이 일어납니다.
이건 선택인 것 같아요.
랜덤 아이콘이 일시적으로 커졌다가 작아지기 vs 전체적으로 깜빡이기
어떤 것이 더 좋지 않은 경험을 주는지 테스트 해보고 싶습니다

랜덤 아이콘 크기가 변동되는 현상 해결

---

client/src/components/document/TuiEditor/useRelativeSearchTerms.ts
client/src/components/document/Write/TitleInputField.tsx
client/src/components/layout/Header/WikiInputField.tsx
client/src/hooks/useFetch.ts

- close #31 
수정 페이지 접속 시 문서 정보를 호출해야 하는데, enabled 초기 값이 없어서 요청이 가지 않는 문제였습니다.
아래처럼 수정해서 enabled를 명시적으로 주지 않으면 자동으로 fetch 해오도록 수정했습니다.
```ts
export const useFetch = <T>(fetchFunction: () => Promise<T>, options: UseFetchOptions = {enabled: true}) => {
...
useEffect(() => {
if (options?.enabled) {
fetchData();
}
}, [fetchData, fetchFunction, options?.enabled]);
}
```

문서 수정이 보이지 않는 문제

---

client/src/app/wiki/[title]/edit/page.tsx
client/src/app/wiki/post/usePostSaveMarkdown.ts
client/src/components/document/TuiEditor/index.tsx
client/src/constants/editor.ts
client/src/context/DocumentWriteContext.tsx

- close #33 
새로운 문서를 작성할 때 닉네임, 생일, 소속/기수, MBTI를 적을 수 있도록 유도했습니다.

문서 작성하기 초기 템플릿 설정

---

client/src/components/common/SearchTerms/RelativeSearchTerms.tsx
client/src/components/layout/Header/WikiInputField.tsx

- close #35 
@언급 쪽에서는 form 태그가 없어서 해당 버튼을 클릭했을 때 그 버튼의 id값을 무사히 가져올 수 있었는데, form 태그 내부에서 onSubmit이 될 event target를 사용하면 form 태그 그 자체가 타겟이 되어버려서 값을 가져올 수 없는 상황이었습니다.
우리의 목표는 submit이 될 때 해당 버튼의 id를 가져오는 것이므로, submit이 일어날 때 submit을 발생 시킨 버튼을 찾아오면 됩니다. submit 이벤트 안에 submit을 발생시킨 submitter를 가져올 수 있고 이를 활용하면 버튼의 id를 가져올 수 있게 됩니다.
```tsx
const submitter = (event.nativeEvent as SubmitEvent).submitter;
const targetTitle = submitter?.id;
```
하지만 여기서 검색 아이콘도 포함되어있어, 이 버튼을 누를 때 예외처리를 해줬습니다.
```tsx
if (targetTitle !== 'search-icon') {
router.push(`${URLS.wiki}/${targetTitle}`);
} else if (titles !== undefined && titles.length !== 0) {
router.push(`${URLS.wiki}/${titles[0]}`);
} else {
router.push(`${URLS.wiki}/${value}`);
}
```

자동 완성 검색 최상단 밖에 클릭이 되지 않는 버그

---

client/package.json
client/src/app/wiki/layout.tsx
client/src/components/common/AmplitudeInitializer/index.tsx
client/src/hooks/mutation/usePostDocument.ts
client/src/hooks/mutation/usePutDocument.ts
client/src/hooks/useAmplitude.ts
client/src/import-env.d.ts
client/yarn.lock

- close #26 
@amplitude/analytics-browser를 사용하여 amplitude를 연결했습니다.
```tsx
init(process.env.NEXT_PUBLIC_AMPLITUDE_API_KEY, {
autocapture: {
elementInteractions: false, // 직접 track 메서드로 이벤트 발생
fileDownloads: false, // 파일 다운로드 할 것 없음
sessions: false, // 로그인이 없어 필요없음
formInteractions: false, // 폼 태그를 트래킹 할 필요 없음
},
});
```
autocapture 옵션으로 사용하지 않을 event를 false로 비활성화 했습니다.
문서가 수정되고 생성될 때 트래킹 코드를 연결하여 이벤트가 발생합니다.
이 이벤트를 추적하여 수정과 생성의 빈도를 측정할 예정입니다.
트래킹 코드는 추후에 더 보강될 수 있습니다.

Amplitude 연결 및 사용자 트래킹 코드 작성

---

client/src/app/api/post-document/route.ts
client/src/app/api/put-document/route.ts

- close #42 
문서 편집과 등록할 때 편집 로그 revalidate 처리를 해주지 않아서 생겼던 문제입니다
아래 getDocumentLogsByTitle를 추가해서 해결했어요!
```ts
revalidateTag(CACHE.tag.getRecentlyDocuments);
revalidateTag(CACHE.tag.getDocumentByTitle(document.title));
revalidateTag(CACHE.tag.getDocumentLogsByTitle(document.title));
```

편집로그가 쌓이지 않는 버그 수정

---

client/src/components/document/Write/TitleInputField.tsx
client/src/hooks/fetch/useGetRecentlyDocuments.ts
client/src/hooks/fetch/useSearchDocumentByQuery.ts

- close #50 
useSearchDocumentByQuery 훅의 파라미터에 query를 넣어줘야 하지만 그렇지 못 해서... 넣어서 해결했습니다.
이 역시 클라이언트에서 프론트 서버로 요청을 보낼 때 no-cache 값을 주지 않아서 생긴 버그,, 해결했습니다.

중복 문서 찾아내지 못함, 새로운 문서 생성 후 참조 불가 버그

---

client/src/components/document/TOC/TOC.tsx
client/src/utils/addDataIdToToc.ts

- close #52 
- heading 태그를 제대로 파싱 하지 못하는 문제
- 히스타, 히스타(7기)처럼 뒤에 붙을 때 전 문서를 가져오지 못하는 문제
사용자가 문서를 작성했을 때 이 오류가 날 가능성이 두 가지 있습니다.
1. 마크다운 to html로 변환할 때 개행의 오류
2. 사용자가 직접 마크다운이 아닌 html로 입력했을 때 h태그 문법을 틀린 상황
아래는 루키(7기) 문서를 보면서 발견한 버그인데, 아마 이 경우는 사용자가 직접 html로 작성한 듯 보였습니다.
그러나 ```<h2>기부천사<h2> 와 같이 </h2>가 아닌 <h2>```로 html 문법을 틀리게 작성한 것 같았습니다.
TOC를 만드는 과정에서 아래 heading 태그를 match를 사용해서 가져올 때 !으로 없을 때도 타입 에러가 나지 않게 했었는데, 여기서 에러가 발생했습니다. match[1]을 접근하려고 할 때 match가 undefined여서 에러를 발생 시켰던 것이 500에러의 원인이었습니다.
```tsx
const match = heading.match(/^<h(\d)/)!;
return parseInt(match[1], 10);
```
그래서 이를 해결하고자 아래와 같이 !를 떼고 match가 없을 때 임의의 값 -1을 돌려주도록 해서 다른 곳을 가리킬지언정 프로그램이 에러가 나지 않도록 설정했습니다.
```tsx
const getHTagOrder = (heading: string) => {
const match = heading.match(/^<h(\d)/);
if (!match) { …
```

문서 조회 실패 버그 해결

---

client/package.json
client/src/apis/images.ts
client/src/components/document/layout/DocumentContents.tsx
client/src/import-env.d.ts
client/src/utils/processHtmlContent.ts
client/src/utils/processImageHtml.ts
client/yarn.lock

- close #58 
기존 이미지를 업로드 할 때 ACL을  public-read로 설정해서 이미지 버킷 내 이미지를 마음껏 접근할 수 있도록 했습니다. 이를 제한하기 위해 위 설정을 제거해줬습니다.
S3 퍼블릭 액세스가 제한됐으므로 S3 주소로 시작하는 url로 이미지를 접근할 수 없게 됐습니다. 이를 해결하기 위해 CloudFront 배포를 활용했습니다. CloudFront domain을 달고 있는 이미지 주소는 S3에 접근할 수 있고 그렇지 않은 이미지 요청은 접근을 제한하도록 설정했습니다. 이를 설정하기 위해 CloudFront에서 OAC를 생성하여 S3 버킷 정책을 업데이트 해줬습니다.
프로젝트를 빌드할 때마다 aws-sdk v2를 사용하지 말라는 경고가 계속 나왔습니다. 이를 해결하기 위해 구글링 한 결과 @aws-sdk/client-s3를 대신 사용하면 된다고 했고, 이에 맞추어 의존성을 변경해줬습니다.
기존에는 aws-sdk에서 AWS를 가져와서 S3를 이용했다면 지금은 client-s3에서 S3Client와 PutObjectCommand 메서드만 가져와 사용하는 방식입니다.
변경된 점을 설명하자면
1) 인스턴스 생성 방식 변경
아래와 같이 S3Client 생성자로 S3 전용 클라이언트를 생성하는 것으로 바뀌었고, 객체 안에 넣어주는 방식이 바뀌었습니다.
```ts
const s3Client = new S3Client({
region,
credentials: {
accessKeyId,
secretAccessKey,
},
});
```
2) content type 명시 …

이미지 버킷 S3 퍼블릭 액세스 차단 및 CloudFront로 액세스하도록 변경

---

client/src/components/document/layout/DocumentTitle.tsx

- close #65 
```tsx
const DocumentTitle = (props: {title: string}) => {
return <h1 className="font-bm text-3xl text-greyscale-800">{props.title}</h1>;
};
export default DocumentTitle;
```
- 현재 위 코드에서 text-greyscale-800 에서 `greyscale` 오타가 있어서 `tailwind.config.js` 에서 사용자 정의한 색상이 적용이 안되는 문제를 해결하였습니다.
- `grayscale`로 오타 수정했습니다.
```tsx
grayscale: {
50: '#F3F4F6',
100: '#E3E3E7',
200: '#D9DADC',
300: '#C7C8CA',
400: '#9FA0A2',
500: '#77787A',
600: '#4F5052',
700: '#36383D',
800: '#27282A',
900: '#18191A',
container: '#F3F4F6',
border: '#E3E3E7',
lightText: '#9FA0A2',
text: '#27282A',
},
```

DocumentTitle 컴포넌트 className 오타 수정

---

.vscode/settings.json
client/package.json
client/yarn.lock

- close #75 
format on save가 적용이 되지 않아서 prettier path를 명시적으로 설정해줬습니다.
vscode 디렉터리 내 settings.json에 아래를 추가했어요!
```json
"prettier.prettierPath": "./client/node_modules/prettier"
```
git fetch를 하셔서 로컬로 불러온 뒤에 prettier format on save가 되는지 테스트 한 번 부탁드립니다!

prettier format on save가 적용되지 않는 문제

---

client/src/utils/processImageHtml.ts

- close #78 
S3 내 모든 이미지 객체에 jpeg 확장자를 붙였습니다. 이전에 AWS 이전을 하며 백업해 둔 이미지가 있었고 그 이미지 정보를 사용해서 확장자가 없는 파일을 jpeg로 덮어 씌웠습니다.
이전에는 확장자가 없는 파일을 요청할 때 `https://~~~/쿠키(6기)/값` 으로 요청을 했는데, 이제는 `https://~~~/쿠키(6기)/값.jpeg`로 요청하기 때문에 이미지를 요청할 때 이미지를 가져오지 못하는 버그가 생길 수 있다고 생각했습니다.
그래서 이미지를 요청하기 전 가공을 해서 이미지 요청 url 뒤에 전부 jpeg를 붙이도록 설정했습니다
1) 확장자가 없으면 jpeg
2) 확장자가 있는데 jpeg가 아니라면 jpeg로 변경

이미지 확장자가 없는 파일 jpeg로 변경 및 대응

---

client/src/apis/client/document.ts
client/src/apis/server/document.ts
client/src/app/wiki/[uuid]/logs/LogContent.tsx
client/src/app/wiki/[uuid]/logs/LogList.tsx
client/src/app/wiki/[uuid]/logs/page.tsx
client/src/components/common/InfinityScrollObserver/index.tsx
client/src/constants/params.ts
client/src/hooks/fetch/useGetDocumentLogs.ts
client/src/type/Document.type.ts

- close #93 
편집 로그를 불러오는 API가 단순 전체 리스트를 응답하는 방식에서 페이지네이션의 형태로 응답하도록 변경됐습니다.
매 번 전체 로그 목록을 불러오는 것에 대한 부담을 덜기 위함이라고 생각이 들었습니다. 그래서 이전에는 전체 페이지를 한 번에 렌더링했지만 이를 반영해서 페이지네이션 응답을 활용해 무한스크롤을 사용해서 데이터를 보여주면 좋겠다는 생각이 들었습니다.
이를 구현하면서 고민점이 있었습니다. 현재 로그 목록 조회 페이지는 서버에서 실행되는 `서버 컴포넌트`입니다.
그러나 무한스크롤을 도입하려면 Scroll 이벤트나 Intersection Observer를 사용해서 마지막 항목을 관측하고 다음 항목을 불러와서 리스트에 붙이는 기능을 추가해야 합니다. 이는 서버 컴포넌트가 아닌 클라이언트 컴포넌트에서 실행되어야 합니다.
이를 해결할 수 있는 방법으로 두 가지 방식을 고민했습니다.
1. 전부 클라이언트 컴포넌트로 처리한다.
2. 첫 페이지는 서버에서 만들고 나머지를 클라이언트에서 처리한다.
고민 결과 2번째 방식으로 구현하기로 결정했습니다. 서버에서 첫 페이지를 빠르게 만들어두고 다음 요청부터 만들어놓은 템플릿을 활용해서 빠르게 응답이 되도록 ISR이 적용되어있는데 이 장점을 활용하면서 나머지 페이지 응답을 뒤에 붙이도록 구현하는 것이 더 좋다고 생각했기 때문입니다.
그래서 첫 페이지는 서버 컴포넌트가 응답해서 페이지를 만들고 그 이후에 유저가 페이지 최하단으로 스크롤하면 다음 페이지를 불러와 붙이도록 구현했습니다.
먼저 페이지 컴포넌트(서버 컴포넌트)에서 데이터를 불러옵니다.
그리고 …

문서 편집로그 페이지네이션으로 불러오는 기능 구현

---

client/src/app/wiki/[uuid]/page.tsx
client/src/utils/getDocumentUsingUUIDInCache.ts

- close #105 
[v3.0.0](https://github.com/Crew-Wiki/crew-wiki-next/pull/101) 이후 https://www.crew-wiki.site/wiki/d 등, 
존재하지 않는 문서의 페이지에 진입하려고 하면  500 Internal Server Error 에러가 발생하는 문제가 있었습니다. 
다만 개발 환경에서는 정상적으로 404 페이지가 표시되고 있었습니다.
프로덕션 환경에서도 정상적인 위키 페이지에 `존재하지 않는 문서에요.` 라는 안내 문구가 노출되도록 개선했습니다.
- 1~5초 : 배포된 사이트
- 6초~ : 개발 환경
https://github.com/user-attachments/assets/b47a0c8d-7e1d-482e-8f3f-b8fcfa35178e
1. `generateMetadata`에 try-catch 추가하여 에러 처리
- 에러 발생 시 기본 메타데이터 반환
`generateMetadata`에서 문제가 발생하고 있었습니다.
```
// 문서가 없으면 Error throw
const documentTitle = await getDocumentTitleUsingUUID(uuid);
// → Error: "캐시에 {uuid}를 가진 문서가 없습니다."
```
이 에러는 catch되지 않아 Next.js 프레임워크 레벨로 전파되어 500 에러가 발생했습니다.
`src/app/wiki/[uuid]/page.tsx` 컴포넌트에서 다음과 같이 구현되어 있습니다. 
```
if (!document) {
notFound(); // 404 페이지로 …
```

존재하지 않는 문서 url에서 500 에러 발생하는 문제 해결

---

client/next.config.ts

- close #104 
- url에 문서의 제목 대신 각 문서의 고유한 uuid를 사용하여 자원을 식별하게 되었습니다.
- 따라서 SEO 설정 변경과 즐겨찾기로 접속하던 사용자들을 변경된 주소로 리다이렉션하는 작업이 요구되었습니다.
- Nextjs는 리다이렉트 시 307, 308 상태 코드를 사용합니다.
- next.config.ts에서 리다이렉트 설정을 할 때 permanent 설정을 할 수 있는데요, 이 값을 false로 설정 시 307 (Temporary Redirect), true로 설정 시 308 (Permanent Redirect) 상태 코드를 갖게 됩니다.
- 논의를 바탕으로 기존 url인 `/wiki/대문`은 더 이상 사용하지 않게 되었고, SEO 점수가 분산되는 것을 막기 위해 permanent 속성을 `true`로 설정했습니다!
|동작 영상|
|---|
|<video src="https://github.com/user-attachments/assets/a946be8a-abf4-43ad-a6f8-1462df33b5a9"/>|
- false로 설정 시 : 검색엔진은 리다이렉트 시킬 대상이 되는 주소를 '나중에 원본 url로 다시 돌아올 수 있다'고 판단해서 기존 주소도 인덱싱을 유지해요. 따라서 SEO 점수가 기존 주소와 새 주소로 분산돼요.
- true로 설정 시 : 검색엔진은 기존 주소를 더 이상 사용하지 않는다고 판단하고 기존 주소 인덱싱은 해제해요. 따라서 시간이 지나면서 SEO 점수가 새로운 주소로만 누적되고, 기존 주소는 검색 결과에서 사라지게 돼요.
- '크루위키'를 구글에 검색 …

대문 리다이렉션 처리

---

client/src/utils/processImageHtml.ts

- close #122 
기존엔 이미지 파일 이름에 .jpg, .png 등 확장자가 있는 경우, 확장자를 .jpeg로 변경하지 않고 그대로 사용했습니다.
확장자가 없는 경우에만 .jpeg를 추가해 주었기 때문에, S3에 저장된 .jpeg 형식의 이미지와 일치하지 않아 이미지가 표시되지 않는 문제가 있었습니다.
그래서 확장자가 있든 없든 모두 jpeg로 변경하도록 하여 이미지가 보이도록 했습니다.
제 문서를 테스트로 본 결과 잘 나오네요. 이전에 안 뜨던 페이지들도 확인했는데 잘 나옵니다.

이미지 불러오기 실패하는 문서 버그 해결
